# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f707a17-3bb1-4949-a87b-4791a9438b1f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0c9b9db8-b55f-43e0-8e6e-33da42473232".device = "/dev/disk/by-uuid/0c9b9db8-b55f-43e0-8e6e-33da42473232";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B555-7F0C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3c37bcac-e95d-4621-8e3d-f0a0cc0112d5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
