# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-9e4b1375-4a3b-4f3d-9dd1-e6e9316b8d56";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-9e4b1375-4a3b-4f3d-9dd1-e6e9316b8d56".device = "/dev/disk/by-uuid/9e4b1375-4a3b-4f3d-9dd1-e6e9316b8d56";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E9D1-8ED8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/games" =
    { device = "/dev/mapper/luks-55d31dfc-fdf2-48b7-8fd7-2904808c9211";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-55d31dfc-fdf2-48b7-8fd7-2904808c9211".device = "/dev/disk/by-uuid/55d31dfc-fdf2-48b7-8fd7-2904808c9211";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/011d3f72-c169-466d-b137-9ca305e0d348"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
