{ config, pkgs, lib, hostUsers,... }:

{
  environment = {
    systemPackages = with pkgs; [
      awscli2
      bash
      bat
      calibre
      cargo
      cloudflared
      cmake
      concurrently
      consul
      curl
      dapr-cli
      delve
      diagridcli
      dig
      direnv
      distrobox
      docker
      docker-compose
      fasd
      fd
      flatpak
      gcc
      gh
      git
      git-crypt
      glibc
      gnumake
      gnupg
      google-cloud-sdk
      grpcurl
      gtop
      helmfile
      htop
      hub
      jq
      jwt-cli
      killall
      kind
      kubectl
      kubectx
      kubernetes
      libsecret
      lm_sensors
      lsof
      lua
      lyrebird
      minikube
      mockgen
      mutter
      mysql-client
      networkmanagerapplet
      nil
      nodePackages.npm
      nodejs
      nomad
      openssl
      openvpn
      p11-kit
      pciutils
      pgcli
      pinentry
      pmutils
      podman
      postgresql
      procps
      protobuf
      pstree
      python3
      ripgrep
      ruby
      rustc
      screen
      shellcheck
      silver-searcher
      socat
      ssh-copy-id
      sysprof
      terraform
      tig
      tmate
      tmux
      tree
      tree-sitter
      unzip
      vim
      watch
      wget
      yarn
      zsh
      unstable.buf
      unstable.fzf
      unstable.go
      unstable.go-migrate
      unstable.go-mockery
      unstable.gofumpt
      unstable.golangci-lint
      unstable.golines
      unstable.gomodifytags
      unstable.gopls
      unstable.gotests
      unstable.gotestsum
      unstable.gotools
      unstable.govulncheck
      unstable.neovim
      unstable.protoc-gen-go
      unstable.protoc-gen-go-grpc
      unstable.universal-ctags
      unstable.yq

      (wrapHelm kubernetes-helm {
        plugins = with pkgs.kubernetes-helmPlugins; [
          helm-diff
        ];
      })
    ];
  };
}
