# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8f91184d-cb1c-4604-a6b8-8ff1a170be13";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-785ba29e-c7b0-4aec-80e4-7f4afebb27a5".device =
    "/dev/disk/by-uuid/785ba29e-c7b0-4aec-80e4-7f4afebb27a5";
  boot.initrd.luks.devices."luks-db159593-8c4d-4c7a-9c36-86331a2fb8eb".device =
    "/dev/disk/by-uuid/db159593-8c4d-4c7a-9c36-86331a2fb8eb";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/59BF-3A56";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/7464ff33-0039-4ecd-a615-c764efcb34e7"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
